-i $UVM_ROOT/env
-i $UVM_ROOT/tests
-i $UVM_ROOT/tb
#AL MOMENTO DE COMPILAR, SE AGREGAN LOS PAQUETES DE ENV, TEST Y EL TOP, SE QUEDA FIJA ESTA ESTRUCTURA
#ESTE ARCHIVO ES EL UNICO QUE SE LLAMA DESDE EL MAKEFILE
$UVM_ROOT/env/top_env_pkg.sv 
$UVM_ROOT/tests/top_test_pkg.sv
$UVM_ROOT/tb/tb.sv